Repository mdsreq-fga-unb/2024.1-Echoeasy, pull requests merged in 2024-09, with the labels that each got.

#49 Feat: Dashboard Web
  echoeasy-web/next.config.mjs
  echoeasy-web/package-lock.json
  echoeasy-web/package.json
  echoeasy-web/src/app/(dash)/documentos/[documentId]/assunto/criar/page.tsx
  echoeasy-web/src/app/(dash)/documentos/[documentId]/page.tsx
  echoeasy-web/src/app/(dash)/documentos/criar/page.tsx
  echoeasy-web/src/app/(dash)/documentos/page.tsx
  echoeasy-web/src/app/(dash)/layout.tsx
  echoeasy-web/src/app/(dash)/minha-conta/page.tsx
  echoeasy-web/src/app/(dash)/page.tsx
  echoeasy-web/src/app/(dash)/usuarios/page.tsx
  echoeasy-web/src/app/(login)/login/page.tsx
  echoeasy-web/src/app/layout.tsx
  echoeasy-web/src/app/page.tsx
  echoeasy-web/src/components/account-details.tsx
  echoeasy-web/src/components/collapse-menu-button.tsx
  echoeasy-web/src/components/content-layout.tsx
  echoeasy-web/src/components/example-charts/interactive-bar-chart.tsx
  echoeasy-web/src/components/login-checker.tsx
  echoeasy-web/src/components/menu.tsx
  echoeasy-web/src/components/mode-toggle.tsx
  echoeasy-web/src/components/navbar.tsx
  echoeasy-web/src/components/sheet-menu.tsx
  echoeasy-web/src/components/sidebar-toggle.tsx
  echoeasy-web/src/components/sidebar.tsx
  echoeasy-web/src/components/ui/avatar.tsx
  echoeasy-web/src/components/ui/chart.tsx
  echoeasy-web/src/components/ui/collapsible.tsx
  echoeasy-web/src/components/ui/combobox.tsx
  echoeasy-web/src/components/ui/command.tsx
  echoeasy-web/src/components/ui/dialog.tsx
  echoeasy-web/src/components/ui/popover.tsx
  echoeasy-web/src/components/ui/scroll-area.tsx
  echoeasy-web/src/components/ui/sheet.tsx
  echoeasy-web/src/components/ui/textarea.tsx
  echoeasy-web/src/components/ui/tooltip.tsx
  echoeasy-web/src/components/user-nav.tsx
  echoeasy-web/src/components/users-table.tsx
  echoeasy-web/src/contexts/TokenContext.tsx
  echoeasy-web/src/hooks/use-sidebar-toggle.ts
  echoeasy-web/src/hooks/use-store.ts
  echoeasy-web/src/hooks/useGetAllAssuntosByDocumentId.ts
  echoeasy-web/src/hooks/useGetAllDocuments.ts
  echoeasy-web/src/hooks/useGetAllUsers.ts
  echoeasy-web/src/hooks/useGetDocumentById.ts
  echoeasy-web/src/lib/menu-list.ts
  echoeasy-web/src/lib/utils.ts
  echoeasy-web/src/services/api.ts
  echoeasy-web/src/services/assuntos.ts
  echoeasy-web/src/services/documents.ts
  echoeasy-web/src/services/services.ts
  echoeasy-web/src/services/user.ts
  echoeasy-web/src/types/user.ts
  echoeasy/src/repositories/documento.repository.ts
Labels: feat, frontend

#56 Feat/app/search
  echoeasy-app/app/(tabs)/_layout.tsx
  echoeasy-app/app/(tabs)/algorithms.tsx
  echoeasy-app/app/(tabs)/documents.tsx
  echoeasy-app/app/(tabs)/more.tsx
  echoeasy-app/components/CategoryTag.tsx
  echoeasy-app/components/ItemCard.tsx
  echoeasy-app/components/SearchInput.tsx
  echoeasy-app/components/modals.tsx/FilterCategoryModal.tsx
  echoeasy-app/package-lock.json
  echoeasy-app/package.json
  echoeasy-app/src/service/CategoryService.ts
  echoeasy-app/src/service/DocService.ts
Labels: feat, frontend

#62 Fix/back/delete
  echoeasy/src/module/documento.module.ts
  echoeasy/src/repositories/assunto.repository.ts
  echoeasy/src/repositories/documento.repository.ts
  echoeasy/src/schema/Assunto.ts
Labels: fix

#63 Feat/back/algoritmo
  echoeasy/src/controller/algoritmo.controller.ts
  echoeasy/src/dto/AlgoritmoCompletoDto.ts
  echoeasy/src/dto/AlgoritmoDto.ts
  echoeasy/src/dto/AlgoritmoUpdateDto.ts
  echoeasy/src/dto/NodeDto.ts
  echoeasy/src/dto/NodeOptionDto.ts
  echoeasy/src/dto/NodeUpdateDto.ts
  echoeasy/src/module/algoritmo.module.ts
  echoeasy/src/module/app.module.ts
  echoeasy/src/repositories/algoritmo.repository.ts
  echoeasy/src/schema/Algoritmo.ts
  echoeasy/src/schema/utils/Node.ts
  echoeasy/src/schema/utils/NodeOption.ts
  echoeasy/src/service/algoritmo.service.ts
Labels: feat, backend

#64 fix: Update import paths for Node and NodeOption schemas
  echoeasy/src/module/algoritmo.module.ts
Labels: fix, backend

#65 Feat: Rota Redefinir Senha
  echoeasy/src/controller/algoritmo.controller.ts
  echoeasy/src/controller/assunto.controller.ts
  echoeasy/src/controller/auth.controller.ts
  echoeasy/src/controller/categoria.controller.ts
  echoeasy/src/controller/documento.controller.ts
  echoeasy/src/controller/usuario.controller.ts
  echoeasy/src/dto/reset-password.dto.ts
  echoeasy/src/module/algoritmo.module.ts
  echoeasy/src/module/app.module.ts
  echoeasy/src/module/assunto.module.ts
  echoeasy/src/module/categoria.module.ts
  echoeasy/src/module/documento.module.ts
  echoeasy/src/service/auth.service.ts
Labels: feat, backend

#66 Feat: Novo esquema de Algoritmo
  echoeasy/src/controller/algoritmo.controller.ts
  echoeasy/src/controller/assunto.controller.ts
  echoeasy/src/dto/AlgoritmoCompletoDto.ts
  echoeasy/src/dto/AlgoritmoDto.ts
  echoeasy/src/dto/AlgoritmoUpdateDto.ts
  echoeasy/src/dto/CreateAlgoritmoDto.ts
  echoeasy/src/dto/NodeDto.ts
  echoeasy/src/dto/NodeOptionDto.ts
  echoeasy/src/dto/NodeUpdateDto.ts
  echoeasy/src/dto/UpdateAlgoritmoDto.ts
  echoeasy/src/module/algoritmo.module.ts
  echoeasy/src/repositories/algoritmo.repository.ts
  echoeasy/src/schema/Algoritmo.ts
  echoeasy/src/service/algoritmo.service.ts
Labels: feat, backend
