Repository mdsreq-fga-unb/2024.1-Echoeasy, pull requests merged in 2024-08, with the labels that each got.

#8 Issues e PR templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/doc.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#31 Feat (backend): Autenticação de Usuário utilizando Firebase
  echoeasy/package-lock.json
  echoeasy/package.json
  echoeasy/src/config/firebase-admin.ts
  echoeasy/src/config/firebase.ts
  echoeasy/src/controller/auth.controller.ts
  echoeasy/src/controller/usuario.controller.ts
  echoeasy/src/dto/UsuarioDto.ts
  echoeasy/src/dto/signin-email.dto.ts
  echoeasy/src/dto/signup-email.dto.ts
  echoeasy/src/guards/auth.guard.ts
  echoeasy/src/module/app.module.ts
  echoeasy/src/module/auth.module.ts
  echoeasy/src/module/usuario.module.ts
  echoeasy/src/schema/Usuario.ts
  echoeasy/src/service/auth.service.ts
  echoeasy/src/service/usuario.service.ts
  echoeasy/tsconfig.json
Labels: feat, backend, Ready

#35 Feat (backend): CRUD de assunto
  echoeasy/src/controller/assunto.controller.ts
  echoeasy/src/dto/AssuntoDto.ts
  echoeasy/src/module/app.module.ts
  echoeasy/src/module/assunto.module.ts
  echoeasy/src/schema/Assunto.ts
  echoeasy/src/service/assunto.service.ts
Labels: feat, backend

#36 chore: Add authentication to Documento and Assunto
  echoeasy/src/controller/assunto.controller.ts
  echoeasy/src/controller/documento.controller.ts
Labels: improvement, backend

#37 Feat (backend): Alterar dados de usuário
  echoeasy/src/controller/usuario.controller.ts
  echoeasy/src/dto/update-usuario.dto.ts
  echoeasy/src/module/usuario.module.ts
  echoeasy/src/service/auth.service.ts
  echoeasy/src/service/usuario.service.ts
Labels: feat, backend, Ready

#39 fix(fix: Refatoração as buscas de entidade por _id no banco): 🐞
  echoeasy/src/controller/assunto.controller.ts
  echoeasy/src/controller/documento.controller.ts
  echoeasy/src/service/assunto.service.ts
  echoeasy/src/service/documento.service.ts
Labels: fix

#38 Feat/backend/role permissions
  echoeasy/src/controller/usuario.controller.ts
  echoeasy/src/decorators/roles.decorator.ts
  echoeasy/src/dto/GetUsuarioDto.ts
  echoeasy/src/dto/UsuarioDto.ts
  echoeasy/src/dto/signup-email.dto.ts
  echoeasy/src/guards/roles.guard.ts
  echoeasy/src/schema/Usuario.ts
  echoeasy/src/service/auth.service.ts
  echoeasy/src/utils/enums/roles.enum.ts
Labels: feat, backend, Ready

#40 Feat/backend/image upload
  echoeasy/src/config/firebase-admin.ts
  echoeasy/src/controller/documento.controller.ts
  echoeasy/src/dto/DocumentoDto.ts
  echoeasy/src/module/documento.module.ts
  echoeasy/src/repositories/documento.repository.ts
  echoeasy/src/schema/Documento.ts
  echoeasy/src/service/documento.service.ts
  echoeasy/src/types/File.ts
Labels: feat, backend

#41 feat: create dashboard with auth structure
  echoeasy-web/.gitignore
  echoeasy-web/package-lock.json
  echoeasy-web/package.json
  echoeasy-web/src/app/layout.tsx
  echoeasy-web/src/app/login/page.tsx
  echoeasy-web/src/app/middleware.ts
  echoeasy-web/src/app/page.tsx
  echoeasy-web/src/components/account-details.tsx
  echoeasy-web/src/components/login-checker.tsx
  echoeasy-web/src/components/login-form.tsx
  echoeasy-web/src/components/ui/button.tsx
  echoeasy-web/src/components/ui/form.tsx
  echoeasy-web/src/components/ui/input.tsx
  echoeasy-web/src/components/ui/label.tsx
  echoeasy-web/src/components/ui/table.tsx
  echoeasy-web/src/components/ui/tabs.tsx
  echoeasy-web/src/components/ui/toast.tsx
  echoeasy-web/src/components/ui/toaster.tsx
  echoeasy-web/src/components/ui/use-toast.ts
  echoeasy-web/src/components/users-table.tsx
  echoeasy-web/src/hooks/hooks.tsx
  echoeasy-web/src/hooks/useToken.tsx
  echoeasy-web/src/types/user.ts
Labels: feat, frontend

#43 Chore: Detalhamento do tratamento de Erros
  echoeasy/src/controller/assunto.controller.ts
  echoeasy/src/controller/documento.controller.ts
  echoeasy/src/controller/usuario.controller.ts
  echoeasy/src/dto/AssuntoDto.ts
  echoeasy/src/repositories/assunto.repository.ts
  echoeasy/src/repositories/documento.repository.ts
  echoeasy/src/repositories/usuario.repository.ts
  echoeasy/src/schema/Assunto.ts
  echoeasy/src/service/assunto.service.ts
  echoeasy/src/service/documento.service.ts
  echoeasy/src/service/usuario.service.ts
Labels: improvement

#47 Feat: Adiciona Collection de Categorias
  echoeasy/src/controller/assunto.controller.ts
  echoeasy/src/controller/categoria.controller.ts
  echoeasy/src/controller/documento.controller.ts
  echoeasy/src/dto/AssuntoDto.ts
  echoeasy/src/dto/CategoriaDto.ts
  echoeasy/src/dto/DocumentoDto.ts
  echoeasy/src/module/app.module.ts
  echoeasy/src/module/categoria.module.ts
  echoeasy/src/repositories/assunto.repository.ts
  echoeasy/src/repositories/categoria.repository.ts
  echoeasy/src/repositories/documento.repository.ts
  echoeasy/src/schema/Assunto.ts
  echoeasy/src/schema/Categoria.ts
  echoeasy/src/schema/Documento.ts
  echoeasy/src/service/assunto.service.ts
  echoeasy/src/service/categoria.service.ts
  echoeasy/src/service/documento.service.ts
Labels: feat, backend

#46 feat/back/delete_user
  echoeasy/src/controller/usuario.controller.ts
  echoeasy/src/repositories/usuario.repository.ts
  echoeasy/src/service/usuario.service.ts
Labels: feat
